/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
} from '@stencil/router';

export namespace Components {
  interface AppProfile {
    'match': MatchResults;
  }
  interface NfyButton {
    'color': 'default' | 'primary' | 'secondary' | undefined;
    'type': 'button' | 'submit' | undefined;
    'variant': 'text' | 'outlined' | 'contained' | undefined;
  }
  interface NfyContainer {}
  interface NfyHeader {}
  interface NfyHome {}
  interface NfyRoot {}
  interface NfyTextarea {
    'name': string;
    'value': string;
  }
  interface NfyTextfield {
    'label': string;
    'name': string;
    'type': 'text' | 'password' | 'email' | undefined;
    'value': string;
  }
  interface NfyTypography {
    'variant': 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p' | undefined;
  }
}

declare global {


  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLNfyButtonElement extends Components.NfyButton, HTMLStencilElement {}
  var HTMLNfyButtonElement: {
    prototype: HTMLNfyButtonElement;
    new (): HTMLNfyButtonElement;
  };

  interface HTMLNfyContainerElement extends Components.NfyContainer, HTMLStencilElement {}
  var HTMLNfyContainerElement: {
    prototype: HTMLNfyContainerElement;
    new (): HTMLNfyContainerElement;
  };

  interface HTMLNfyHeaderElement extends Components.NfyHeader, HTMLStencilElement {}
  var HTMLNfyHeaderElement: {
    prototype: HTMLNfyHeaderElement;
    new (): HTMLNfyHeaderElement;
  };

  interface HTMLNfyHomeElement extends Components.NfyHome, HTMLStencilElement {}
  var HTMLNfyHomeElement: {
    prototype: HTMLNfyHomeElement;
    new (): HTMLNfyHomeElement;
  };

  interface HTMLNfyRootElement extends Components.NfyRoot, HTMLStencilElement {}
  var HTMLNfyRootElement: {
    prototype: HTMLNfyRootElement;
    new (): HTMLNfyRootElement;
  };

  interface HTMLNfyTextareaElement extends Components.NfyTextarea, HTMLStencilElement {}
  var HTMLNfyTextareaElement: {
    prototype: HTMLNfyTextareaElement;
    new (): HTMLNfyTextareaElement;
  };

  interface HTMLNfyTextfieldElement extends Components.NfyTextfield, HTMLStencilElement {}
  var HTMLNfyTextfieldElement: {
    prototype: HTMLNfyTextfieldElement;
    new (): HTMLNfyTextfieldElement;
  };

  interface HTMLNfyTypographyElement extends Components.NfyTypography, HTMLStencilElement {}
  var HTMLNfyTypographyElement: {
    prototype: HTMLNfyTypographyElement;
    new (): HTMLNfyTypographyElement;
  };
  interface HTMLElementTagNameMap {
    'app-profile': HTMLAppProfileElement;
    'nfy-button': HTMLNfyButtonElement;
    'nfy-container': HTMLNfyContainerElement;
    'nfy-header': HTMLNfyHeaderElement;
    'nfy-home': HTMLNfyHomeElement;
    'nfy-root': HTMLNfyRootElement;
    'nfy-textarea': HTMLNfyTextareaElement;
    'nfy-textfield': HTMLNfyTextfieldElement;
    'nfy-typography': HTMLNfyTypographyElement;
  }
}

declare namespace LocalJSX {
  interface AppProfile extends JSXBase.HTMLAttributes<HTMLAppProfileElement> {
    'match'?: MatchResults;
  }
  interface NfyButton extends JSXBase.HTMLAttributes<HTMLNfyButtonElement> {
    'color'?: 'default' | 'primary' | 'secondary' | undefined;
    'type'?: 'button' | 'submit' | undefined;
    'variant'?: 'text' | 'outlined' | 'contained' | undefined;
  }
  interface NfyContainer extends JSXBase.HTMLAttributes<HTMLNfyContainerElement> {}
  interface NfyHeader extends JSXBase.HTMLAttributes<HTMLNfyHeaderElement> {}
  interface NfyHome extends JSXBase.HTMLAttributes<HTMLNfyHomeElement> {}
  interface NfyRoot extends JSXBase.HTMLAttributes<HTMLNfyRootElement> {}
  interface NfyTextarea extends JSXBase.HTMLAttributes<HTMLNfyTextareaElement> {
    'name'?: string;
    'onHandleInput'?: (event: CustomEvent<any>) => void;
    'value'?: string;
  }
  interface NfyTextfield extends JSXBase.HTMLAttributes<HTMLNfyTextfieldElement> {
    'label'?: string;
    'name'?: string;
    'onHandleInput'?: (event: CustomEvent<any>) => void;
    'type'?: 'text' | 'password' | 'email' | undefined;
    'value'?: string;
  }
  interface NfyTypography extends JSXBase.HTMLAttributes<HTMLNfyTypographyElement> {
    'variant'?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p' | undefined;
  }

  interface IntrinsicElements {
    'app-profile': AppProfile;
    'nfy-button': NfyButton;
    'nfy-container': NfyContainer;
    'nfy-header': NfyHeader;
    'nfy-home': NfyHome;
    'nfy-root': NfyRoot;
    'nfy-textarea': NfyTextarea;
    'nfy-textfield': NfyTextfield;
    'nfy-typography': NfyTypography;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


